version: "3.8"

services:
  nextjs:
    image: node:20.1.0-alpine
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # 내부에서 3000 포트를 사용
    environment:
      - NODE_ENV=production
    restart: always
